# Generated by Django 4.2.2 on 2023-09-16 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dependapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project',
            new_name='projectname',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='site',
            new_name='sitename',
        ),
        migrations.AlterField(
            model_name='site',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dependapp.project'),
        ),
    ]
